export const DefaultTheme = {
  colors: {
    colorMainRed: '#F42F46',
    colorLightRed: '#FBF4F4',
    colorBlack: '#4A4A4A',
    colorGray: '#8c94a8',
    colorWhite: '#FFFFFF',
    colorButtonPrimary: '#ffffff',
    colorButtonText: '#E11439',
    colorSlideshowButton: '#F42F46',
    colorSlideshowPagination: '#FFFFFF',
    colorSlideshowPaginationActive: '#F42F46',
    colorSlideshowTitle: '#FFFFFF',
    backgroundButtonPrimary: '#ff0d29',
    backgroundHeader: '#ffffff',
    promoGradient:
      'linear-gradient(90deg, rgba(244,47,70,1) 0%, rgba(225,20,57,1) 100%)',
    colorWarning: '#d10a34',
    colorSuccess: '#52bc77',
    colorActive: '#1e90ff',
    borderInput: '#ededed',
    boxShadowMain: '#D2CACA',
    boxShadowHover: '#C0BDBD',
  },
  deviceSizes: {
    mobileSmall: '375px',
    mobile: '576px',
    tablet: '904px',
    laptop: '1240px',
  },
  fontSizes: {
    desktop: {
      xxl: '60px',
      xl: '38px',
      l: '28px',
      m: '22px',
      s: '16px',
      xs: '14px',
    },
    laptop: {
      xxl: '60px',
      xl: '38px',
      l: '28px',
      m: '20px',
      s: '16px',
      xs: '14px',
    },
    tablet: {
      xxl: '50px',
      xl: '38px',
      l: '26px',
      m: '22px',
      s: '16px',
      xs: '14px',
    },
    mobile: {
      xxl: '45px',
      xl: '32px',
      l: '24px',
      m: '18px',
      s: '16px',
      xs: '14px',
    },
    mobileSmall: {
      xxl: '40px',
      xl: '28px',
      l: '22px',
      m: '16px',
      s: '16px',
      xs: '14px',
    }
  },

};
